# Numpy Tutorial (One Shot)
---

In [2]:
import numpy as np
import matplotlib.pylab as plt

>#### Creating Arrays

In [13]:
# creating a numpy array from a python list and specifying data type
py_list = [1,2,3,4,5]
np_arr_1 = np.array(py_list, dtype=np.int8)
np_arr_1

# creating a range of values in array with step=2
np.arange(1,10,2)

# creating 6 equally spaced values between 0 and 5
np.linspace(0,5,6)

# creating a list of zeros/ones
np.zeros(5)
np.zeros((2,3))
np.ones(5)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# returns the dimension of array (rows, cols)
np_arr_1.shape

# returns number of elements inside an array
np_arr_1.size

# returns data type of each element
np_arr_1.dtype

# generate random arrays single/multi-dimentional
np.random.randint(1, 10, 4)
np.random.randint(1, 10, size=(3,3))

array([[5, 3, 1],
       [8, 4, 8],
       [1, 3, 6]])

>#### Slicing and Indexes

In [49]:
np_arr_3 = np.random.randint(0, 10, size=(3,3))
np_arr_3

array([[4, 2, 1],
       [6, 4, 7],
       [4, 0, 5]])

In [69]:
# assigning a value at a particular index
np_arr_3.itemset((0,0), -1)

# get a value from array at a particular index/indices
np_arr_3[1,2]
np_arr_3.item(1,2)
np_arr_3[1:,2]

# returns a set of values satisfying condition
# even nos
np_arr_3[np_arr_3%2 == 0]
# greater than 4
np_arr_3[np_arr_3 > 4]
# greater than 2 and less than equal to 6
np_arr_3[(np_arr_3 > 2) & (np_arr_3 <= 6)] 

# unique values
np.unique(np_arr_3)

array([-1,  0,  1,  2,  4,  5,  6,  7])

>#### Reshaping, Resizing, Sorting Arrays

In [85]:
print(np_arr_3)
# reshpaing arrays to a diff dimension
np_arr_3.reshape(1,9)
np.resize(np_arr_3, (1,9))

# transposing/swapping elements
np_arr_3.transpose()

# flattening array (making it one-dimensional)
np_arr_3.flatten()    # by row order
np_arr_3.flatten('F') # by col order

# sorting by row/col
np_arr_3.sort(axis=0)
np_arr_3.sort(axis=1)

[[-1  0  1]
 [ 2  4  5]
 [ 4  6  7]]


array([-1,  2,  4,  0,  4,  6,  1,  5,  7])

>#### Stacking and Splitting

In [97]:
np_zeros = np.zeros(9).reshape(3,3)
np_ones = np.ones(9).reshape(3,3)


In [101]:
# vertical stacking
np.vstack((np_zeros, np_ones))

# horizontal stacking
np.hstack((np_zeros, np_ones))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

>#### Basic Math

In [142]:
np_arr_5 = np.arange(0,10)
np_arr_6 = np.arange(10,20)
np_arr_7 = np.arange( 0,20).reshape(4,5)

# basic operations
np_arr_5 + np_arr_6
np_arr_5 - np_arr_6
np_arr_5 * np_arr_6
np_arr_5 / np_arr_6

# sum of all elements
np_arr_5.sum()

# sum of values iterating thro rows/cols
np_arr_5.reshape(2,5).sum(axis=0)

# max value in each row/col
np_arr_5.reshape(2,5).max(axis=0)
np_arr_5.reshape(2,5).max(axis=1)

# returns row index of max value in col
np_arr_7.argmax(axis=0)

# returns col index of max value in row
np_arr_7.argmax(axis=1)

array([4, 4, 4, 4], dtype=int64)

>#### Linear Algebra

In [144]:
from numpy import linalg as LA

In [159]:
np_arr_8 = np.random.randint(0,10, size=(2,2))
np_arr_9 = np.random.randint(0,10, size=(2,2))

In [164]:
# calculating the determinant of a matrix
LA.det(np_arr_8)

# dot product
np.dot(np_arr_8, np_arr_9)

# solving linear equations:
# x + 4y = 10
# 6x + 18y = 42
def linear_eq_solver(x_coeff_1, y_coeff_1, value_1, x_coeff_2, y_coeff_2, value_2):
    arr_coeff = np.array([[x_coeff_1, y_coeff_1],[x_coeff_2, y_coeff_2]])
    arr_values = np.array([value_1, value_2])
    return LA.solve(arr_coeff, arr_values)

x_value, y_value = linear_eq_solver(1, 4, 10, 6, 18, 42)
print(f"x = {x_value}, y = {y_value}")

x = -2.0, y = 3.0
