# Numpy Tutorial Playlist
---

Ref [CodeBasics]: https://www.youtube.com/watch?v=rN0TREj8G7U&list=PLUcmakntVocWGSKXIsUn1J7Wm9ekpZ87G 

(Playlist of 6 videos)

>#### Numpy Arrays vs Python Lists

- Numpy Arrays (`np.array([element1, element2 ..])`) use less memory, are fast and more convenient than traditional arrays

In [1]:
import numpy as np

In [8]:
# time taken to add a million elements of 2 lists
import time

size = 1000000

list_1 = range(size)
list_2 = range(size)

numpy_list_1 = np.arange(size)
numpy_list_2 = np.arange(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(list_1, list_2)]
print("Python list took {} miliseconds".format((time.time() - start)*1000))

# numpy array
start = time.time()
numpy_list_1 + numpy_list_2
print("Numpy Array took {} miliseconds".format((time.time() - start)*1000))

Python list took 274.5041847229004 miliseconds
Numpy Array took 2.990245819091797 miliseconds


>#### Datatypes, Shaping, Reshaping

In [55]:
a = np.array([1,2,3,4])

a.dtype # returns the data type of the element in the array
type(a) # returns the 

# gives the dimension of the array
a.ndim

# changing the data type
a_float = np.array([1,2,3,4], dtype=np.float64)
a_float.itemsize

# checking the bitesize of each item
print("{} holds {} bytes".format(a.dtype, a.itemsize))
print("{} holds {} bytes".format(a_float.dtype, a_float.itemsize))

# size of the array
a_float.size

# rows, columns within an array
b = np.array([[1,2],[3,4],[5,6]])
print(b.shape)

# reshape array
b.reshape(2,3)

# flatten array i.e. make it one dimensional
b.ravel()

# table of zeroes
zeros_3by4 = np.zeros((3,4)) #(rows,cols)
print(zeros_3by4)

# table of ones
ones_4by4 = np.ones((4,4)) #(rows,cols)
print(ones_4by4)

int32 holds 4 bytes
float64 holds 8 bytes
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


***Note:*** Functions like `.reshape()`, `.ravel()` don't alter the original array - they instead return a new array that can be stored inside a new variable

>#### Creating Ranges

In [49]:
# range of values
range_0to5 = np.arange(0,6,1) # (start, end, step)
range_0to5

# creating x linearly space numbers between start_num and end_num
range_0to10  = np.linspace(0,10,11) # (start, end, x): x = nums between start and end
range_0to10

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

>#### Basic Maths/Stats Functions

In [87]:
c = np.arange(0,11)
d = np.array([[1,2],[3,4],[5,6]])

# return smallest element
c.min()

# return largest element
c.max()

# sum of all elements in the array
c.sum()

# using axis argument to return sum in multi-dimentional array
d.sum(axis=1) # axis=0: iterate thro columns, axis=1: iterate thro rows

# square root of all elements
np.sqrt(c)

# standard deviation of a list
np.std(c)

3.1622776601683795

>#### Operations between Arrays

In [98]:
e = np.arange(1,11)
f = np.arange(11,21)

e+f # add
e-f # subtract
e/f # divide
e*f # multiply

# matrix product
g = np.array([[1,2],[3,4]])
h = np.array([[5,6],[7,8]])
g.dot(h)

array([[19, 22],
       [43, 50]])

>#### Slicing, Stacking, Indexing with Boolean arrays

In [106]:
i = np.array([5,6,7,8,9])
j = np.array([[9,10,11],[12,13,14],[15,16,17]])

i[0:2] # slicing
i[-1]  # reverse indexing
j[1:3,1] # multi-dimensional indexing; [rows,cols]


array([13, 16])

In [138]:
k = np.arange(6).reshape(3,2)
l = np.arange(6,12).reshape(3,2)

np.vstack((k,l)) # stack vertically
np.hstack((k,l)) # stack horizontally

m = np.arange(1,31).reshape(3,10)

# horizontal split into x equal sections
m_hsplit = np.hsplit(m,2)
m_hsplit[0] # call a section by index

# vertical split into x equal sections
m_vsplit = np.vsplit(m,3)
m_vsplit[1] # call a section by index

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [149]:
n = np.arange(1,21).reshape(5,4)

o = n > 10 # boolean condition

# prints those values which satisfy the above
n[o] 

# replaced all elements that satisfy the above condition with '-1'
n[o] = -1
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

>#### Iterating through Numpy arrays

In [14]:
# using for loop(s)
p = np.arange(12).reshape(3,4)

for row in p:
    for element in row:
        print(element)

# OR

for element in p.flatten():
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
# using nditer

# iterating row-by-row, printing each element
for x in np.nditer(p,order="C"):
    print(x)

# iterating column-by-column, printing each element
for x in np.nditer(p,order="F"):
    print(x)

# iterating column-by-column, printing each column
for x in np.nditer(p,order="F",flags=["external_loop"]):
    print(x)

# iterating through each element and modifying it
for x in np.nditer(p,op_flags=["readwrite"]):
    x[...]=x*x # returns the square of each element in the array

0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [18]:
q = np.arange(1,13).reshape(3,4)
r = np.arange(1,4).reshape(3,1)

# iterating through 2 arays
for q_ele, r_ele in np.nditer([q,r]):
    print(q_ele, r_ele)


1 1
2 1
3 1
4 1
5 2
6 2
7 2
8 2
9 3
10 3
11 3
12 3


**General Array Broadcasting Rules**: Two dimensions are compatible when...
- They are equal
- One of them is 1

For eg: A shape of (3,2) is compatible with = (3,2), (3,1), (1,2)